In [1]:
import numpy as np

In [12]:
weights = np.array([.5,0,-.5])

In [13]:
alpha = 0.1

In [14]:
# unlabeled data
x = np.array([
        [1,0,1],
        [0,1,1],
        [0,0,1],
        [1,1,1],
        [0,1,1],
        [1,0,1]
    ])

In [15]:
# correct values
y = np.array([0,1,0,1,1,0])

In [16]:
for iteration in range(10):
    J_cost_function = 0
    for  row_index in range(len(y)):
        input = x[row_index]
        actual = y[row_index]

        prediction = input.dot(weights)
        error = (actual - prediction) ** 2
        J_cost_function += error

        delta = prediction - actual
        weights = weights - (alpha * (input * delta))
        print(prediction)
    print('error ' + str(J_cost_function))
    print(weights)
        

0.0
-0.5
-0.35
0.335
-0.032
0.4212
error 4.05715844
[ 0.52438  0.3197  -0.18742]
0.33696
0.098584
-0.1309744
0.78264864
0.335434912
0.4827338208
error 1.66516745174
[ 0.46414575  0.49803324 -0.0779587 ]
0.38618705664
0.381455841856
-0.0547229871296
0.936164020454
0.523404168107
0.436703138938
error 0.956660174431
[ 0.38824033  0.61393084 -0.03887782]
0.34936251115
0.540116769477
-0.0278257492292
0.988180071706
0.637239976163
0.366900894938
error 0.600671834539
[ 0.31779598  0.69737716 -0.02427527]
0.29352071595
0.643749819842
-0.0180023221662
1.00524400103
0.715751287883
0.299617893998
error 0.383988397449
[ 0.25795772  0.76090265 -0.01826341]
0.239694315198
0.718669809387
-0.0140998206995
1.0103341215
0.77427900528
0.241803728462
error 0.246324650455
[ 0.20877451  0.81057436 -0.01533152]
0.19344298277
0.775898533101
-0.0122656757407
1.0113756027
0.819670273514
0.194148952588
error 0.158134132233
[ 0.16887775  0.84987991 -0.01355859]
0.15531916207
0.820789407346
-0.0111694479886
1.0110